import { Policy, SurgicalCase } from "@/types/domain";

export const mockCases: SurgicalCase[] = [
  {
    caseId: "CASE-001",
    patientName: "Ana Mendez",
    documentId: "ID-90001",
    policyId: "POL-100",
    diagnosis: "Colelitiasis sintomatica",
    requestedProcedure: "Colecistectomia laparoscopica",
    requestDate: "2026-05-12",
    medicalReport: "Paciente con dolor abdominal recurrente y estudio ecografico compatible con colelitiasis.",
    submittedDocuments: ["informe_medico", "orden_quirurgica"],
    status: "Nuevo",
    finalResult: "",
    decisionReason: "",
    missingDocumentsText: [],
    extractionConfidence: 0,
    processedAt: "",
  },
  {
    caseId: "CASE-002",
    patientName: "Luis Herrera",
    documentId: "ID-90002",
    policyId: "POL-101",
    diagnosis: "Hernia inguinal",
    requestedProcedure: "Hernioplastia inguinal",
    requestDate: "2026-05-12",
    medicalReport: "Se recomienda correccion quirurgica por dolor y compromiso funcional.",
    submittedDocuments: ["informe_medico"],
    status: "Nuevo",
    finalResult: "",
    decisionReason: "",
    missingDocumentsText: [],
    extractionConfidence: 0,
    processedAt: "",
  },
  {
    caseId: "CASE-003",
    patientName: "Carla Paredes",
    documentId: "ID-90003",
    policyId: "POL-102",
    diagnosis: "Desviacion septal funcional",
    requestedProcedure: "Rinoplastia estetica",
    requestDate: "2026-05-12",
    medicalReport: "Informe enfocado en mejora estetica sin compromiso funcional severo.",
    submittedDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
    status: "Nuevo",
    finalResult: "",
    decisionReason: "",
    missingDocumentsText: [],
    extractionConfidence: 0,
    processedAt: "",
  },
  {
    caseId: "CASE-004",
    patientName: "Marco Salazar",
    documentId: "ID-90004",
    policyId: "POL-103",
    diagnosis: "Litiasis renal obstructiva",
    requestedProcedure: "Ureteroscopia",
    requestDate: "2026-05-12",
    medicalReport: "Dolor intenso, obstruccion y criterio de intervencion endoscopica.",
    submittedDocuments: ["informe_medico", "orden_quirurgica"],
    status: "Nuevo",
    finalResult: "",
    decisionReason: "",
    missingDocumentsText: [],
    extractionConfidence: 0,
    processedAt: "",
  },
];

export const mockPolicies: Policy[] = [
  {
    policyId: "POL-100",
    insurerName: "Salud Segura",
    plan: "Integral",
    policyStartDate: "2026-02-20",
    coveredProcedures: ["Colecistectomia laparoscopica", "Apendicectomia"],
    exclusions: ["Cirugia estetica"],
    waitingPeriodDays: 30,
    requiredDocuments: ["informe_medico", "orden_quirurgica"],
    specialRules: "",
  },
  {
    policyId: "POL-101",
    insurerName: "Salud Segura",
    plan: "Estandar",
    policyStartDate: "2026-03-28",
    coveredProcedures: ["Hernioplastia inguinal"],
    exclusions: ["Cirugia experimental"],
    waitingPeriodDays: 60,
    requiredDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
    specialRules: "",
  },
  {
    policyId: "POL-102",
    insurerName: "Salud Segura",
    plan: "Estandar",
    policyStartDate: "2026-05-01",
    coveredProcedures: ["Septoplastia", "Amigdalectomia"],
    exclusions: ["Rinoplastia estetica", "Cirugia estetica"],
    waitingPeriodDays: 90,
    requiredDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
    specialRules: "",
  },
  {
    policyId: "POL-103",
    insurerName: "Salud Segura",
    plan: "Premium",
    policyStartDate: "2026-05-01",
    coveredProcedures: ["Ureteroscopia", "Litotricia"],
    exclusions: ["Cirugia experimental"],
    waitingPeriodDays: 45,
    requiredDocuments: ["informe_medico", "orden_quirurgica"],
    specialRules: "",
  },
];
