import { Policy, SurgicalCase } from "@/types/domain";

export const mockCases: SurgicalCase[] = [
  {
    caseId: "CASE-001",
    patientName: "Ana Mendez",
    insurerName: "Salud Segura",
    policyId: "POL-100",
    policyStartDate: "2026-02-20",
    diagnosis: "Colelitiasis sintomatica",
    requestedProcedure: "Colecistectomia laparoscopica",
    requestDate: "2026-05-12",
    submittedDocuments: ["informe_medico", "orden_quirurgica"],
    isUrgent: false,
    status: "Nuevo",
  },
  {
    caseId: "CASE-002",
    patientName: "Luis Herrera",
    insurerName: "Salud Segura",
    policyId: "POL-101",
    policyStartDate: "2026-03-28",
    diagnosis: "Hernia inguinal",
    requestedProcedure: "Hernioplastia inguinal",
    requestDate: "2026-05-12",
    submittedDocuments: ["informe_medico"],
    isUrgent: false,
    status: "Nuevo",
  },
  {
    caseId: "CASE-003",
    patientName: "Carla Paredes",
    insurerName: "Salud Segura",
    policyId: "POL-102",
    policyStartDate: "2026-05-01",
    diagnosis: "Desviacion septal funcional",
    requestedProcedure: "Rinoplastia estetica",
    requestDate: "2026-05-12",
    submittedDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
    isUrgent: false,
    status: "Nuevo",
  },
  {
    caseId: "CASE-004",
    patientName: "Marco Salazar",
    insurerName: "Salud Segura",
    policyId: "POL-103",
    policyStartDate: "2026-05-01",
    diagnosis: "Litiasis renal obstructiva",
    requestedProcedure: "Ureteroscopia",
    requestDate: "2026-05-12",
    submittedDocuments: ["informe_medico", "orden_quirurgica"],
    isUrgent: false,
    status: "Nuevo",
  },
];

export const mockPolicies: Policy[] = [
  {
    policyId: "POL-100",
    insurerName: "Salud Segura",
    coveredProcedures: ["Colecistectomia laparoscopica", "Apendicectomia"],
    exclusions: ["Cirugia estetica"],
    waitingPeriodDays: 30,
    requiredDocuments: ["informe_medico", "orden_quirurgica"],
  },
  {
    policyId: "POL-101",
    insurerName: "Salud Segura",
    coveredProcedures: ["Hernioplastia inguinal"],
    exclusions: ["Cirugia experimental"],
    waitingPeriodDays: 60,
    requiredDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
  },
  {
    policyId: "POL-102",
    insurerName: "Salud Segura",
    coveredProcedures: ["Septoplastia", "Amigdalectomia"],
    exclusions: ["Rinoplastia estetica", "Cirugia estetica"],
    waitingPeriodDays: 90,
    requiredDocuments: ["informe_medico", "orden_quirurgica", "copia_poliza"],
  },
  {
    policyId: "POL-103",
    insurerName: "Salud Segura",
    coveredProcedures: ["Ureteroscopia", "Litotricia"],
    exclusions: ["Cirugia experimental"],
    waitingPeriodDays: 45,
    requiredDocuments: ["informe_medico", "orden_quirurgica"],
  },
];
